apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: postgres-svc
spec:
  ports:
  - port: 5432
  clusterIP: None
  selector:
    # any pods with this 'postgres' label belongs to this service
    app: postgres