apiVersion: v1
kind: Service
metadata:
  name: ping-pong-svc
  namespace: exercises
spec:
  type: ClusterIP
  selector:
    app: ping-pong
  ports:
  - protocol: TCP
    port: 2347
    targetPort: 3002
