apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-log-pvc
spec:
  storageClassName: shared-log-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
