apiVersion: v1
kind: ConfigMap
metadata:
  name: log-output-configmap
  namespace: exercises
data:
  information.txt: "this text is from file"
  MESSAGE: "hello world"
  PING_PONG_URL: "http://ping-pong-svc:2347/pingpong"

