apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
      - name: log-output
        image: yonggsnap/log-output:2.4
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        env:
        - name: PORT
          value: "3001"
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: log-output-configmap
              key: MESSAGE
      volumes:
      - name: config-volume
        configMap:
          name: log-output-configmap