apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
      - name: log-storage
        persistentVolumeClaim:
          claimName: shared-log-pvc
      containers:
      - name: log-output
        image: yonggsnap/log-output:2.2
        env:
        - name: PORT
          value: "3001"
        volumeMounts:
        - name: log-storage
          mountPath: /usr/src/app/files